apiVersion: v1
kind: Service
metadata:
    name: myProfile-Service
spec:
   type: LoadBalancer
   ports: 
      - port: 80
        targetPort: 3000
    selector: 
       app: myProfile

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myProfile-Deployment
spec: 
  replicas: 2
  template: 
    metadata: 
      labels:
        app: myProfile
    spec:
      containers:
        - name: myProfile
          imagePullPolicy: Always
          image: antodocker/myprofile:latest
          ports:
            - containerPort: 3000
