apiVersion: v1
kind: Service
metadata:
    name: myprofileservice
spec:
   type: LoadBalancer
   ports: 
      - port: 80
        targetPort: 3000
   selector: 
      app: myprofile

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myprofiledeployment
spec: 
  replicas: 1
  template: 
    metadata: 
      labels:
        app: myprofile
    spec:
      containers:
        - name: myprofileapi
          imagePullPolicy: Always
          image: antodocker/myprofile:latest
          ports:
            - containerPort: 3000
