apiVersion: v1
kind: Pod
metadata: 
    name: myprofile-pod
    labels:
        - app: myprofile
        - status:  approved
spec: 
    containers:
        - name: myprofile-api
          image: antodocker/myprofile:17
          ports: 3000
          env: 
           - name: PORT
             value: 4000
          imagePullPolicy: Always


