apiVersion: v1
kind: Pod
metadata: 
    name: myprofile-pod
    labels:
        app: myprofile        
spec: 
    containers:
      - env: 
         - name: PORT
           value: 4000
           name: myprofile-api
           image: antodocker/myprofile:latest
                    
           


